### ISSUE TITLE
Sandpolis Viewer not starting

### ISSUE THREAD

**Issue by mrkaban** [fossable/sandpolis#291]
![Снимок](https://user-images.githubusercontent.com/14289360/77221612-b762a200-6b7d-11ea-8f59-7e28d03ebef0.jpg)
I decided to try an interesting program for remote control on two computers, both Windows 10 64 bit. Both computers have the latest Java installed.

On one, I installed only Sandpolis Viewer to connect from it to a second computer. The program has been installed, but at startup it gives an error "Error: Could not create the Java Virtual Machine. Error: A fatal exception has occurred. Program will exit.".

On the second computer, even the installer did not start, it issued the error "Error: A JNI error has occurred, please check your installation and try again".

**Comment by cilki** [comment]
Maybe your JVM isn’t started with enough memory? Try increasing your heap limit. If that works than I can set it automatically at runtime.

I don’t test on Windows currently (not enough hours in the day), so you’re going to find plenty of other broken things too :)

**Comment by mrkaban** [comment]
I have a popular site (about 1300 people a day) with free programs for Windows, and I often test programs for later additions. Other Java applications started without problems. 12 gigabytes of RAM are available.

In this case, you can close the ticket.

**Comment by cilki** [comment]
I’ve seen others with this same problem, so I’ll leave the issue open until I get a chance to actually address it. Thanks.
